[".config/nvim"]
  type = "archive"
  # renovate: currentValue=main
  url = "https://github.com/kabinspace/AstroVim/archive/4b60cfd5d7633f20a2133d31dacd77b61b734e47.zip"
  exact = false
  stripComponents = 1
  # include = [
  #   "*/colors/**/*",
  #   "*/lua/**/*",
  #   "*/init.lua",
  #   "*/.luacheckrc",
  #   "*/.stylua.toml"
  # ]
[".local/share/lunarvim/lvim"]
  type = "archive"
  # renovate: currentValue=rolling
  url = "https://github.com/LunarVim/LunarVim/archive/36361e1107d80e2eb2d8d90afebcff40f1198764.zip"
  exact = true
  stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}

