{{- if eq .chezmoi.os "linux" }}
[".icons/macOS-Monterey"]
  type = "archive"
  url = "https://github.com/ful1e5/apple_cursor/releases/latest/download/macOS-Monterey.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"

[".icons/macOS-Monterey-White"]
  type = "archive"
  url = "https://github.com/ful1e5/apple_cursor/releases/latest/download/macOS-Monterey-White.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"

# [".config/awesome/modules/vicious"]
#   type = "archive"
#   # renovate: currentValue=master
#   url = "https://github.com/vicious-widgets/vicious/archive/4d3025400e565958aadb0738a1dba388fa543d44.zip"
#   exact = true
#   stripComponents = 1

# [".config/awesome/modules/bling"]
#   type = "archive"
#   # renovate: currentValue=master
#   url = "https://github.com/BlingCorp/bling/archive/d670537bea77e70e17f57845e3a3545b53291945.zip"
#   exact = true
#   stripComponents = 1
{{- end }}
