[".config/nvim"]
  type = "archive"
  # renovate: currentValue=main
  url = "https://github.com/kabinspace/AstroVim/archive/fac241cf79580282e96fec7a3c8e10033bdce4dd.zip"
  exact = false
  stripComponents = 1
  include = [
    "*/lua/**/*",
    "*/init.lua",
    "*/.luacheckrc",
    "*/.stylua.toml"
  ]
# [".config/nvim"]
#   type = "git-repo"
#   url = "https://github.com/kabinspace/AstroVim.git"
#   refreshPeriod = "24h"
{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}
