{{- if eq .chezmoi.os "linux" }}
[".icons/macOS"]
  type = "archive"
  url = "https://github.com/ful1e5/apple_cursor/releases/download/v2.0.1/macOS.tar.xz"
  exact = true
  stripComponents = 2
  refreshPeriod = "72h"

# [".icons/macOS-White"]
#   type = "archive"
#   url = "https://github.com/ful1e5/apple_cursor/releases/latest/download/macOS-White.tar.xz"
#   exact = true
#   stripComponents = 1
#   refreshPeriod = "72h"

[".config/awesome/vicious"]
  type = "archive"
  # renovate: currentValue=master
  url = "https://github.com/vicious-widgets/vicious/archive/4d3025400e565958aadb0738a1dba388fa543d44.zip"
  exact = true
  stripComponents = 1

[".config/awesome/bling"]
  type = "archive"
  # renovate: currentValue=master
  url = "https://github.com/BlingCorp/bling/archive/19ccfc0daf5edda8bbc508487616d00277a9d954.zip"
  exact = true
  stripComponents = 1

[".config/awesome/rubato"]
  type = "archive"
  # renovate: currentValue=main
  url = "https://github.com/andOrlando/rubato/archive/8a3737b7af4c9dc40c53d700118333d36541d4d3.zip"
  exact = true
  stripComponents = 1
{{- end }}
