{{- if eq .chezmoi.os "linux" }}
[".icons/macOS"]
  type = "archive"
  url = "https://github.com/ful1e5/apple_cursor/releases/download/v2.0.1/macOS.tar.xz"
  exact = true
  stripComponents = 2
  refreshPeriod = "72h"
  include = ["*/macOS/**"]

[".icons/macOS-White"]
  type = "archive"
  url = "https://github.com/ful1e5/apple_cursor/releases/download/v2.0.1/macOS.tar.xz"
  exact = true
  stripComponents = 2
  refreshPeriod = "72h"
  include = ["*/macOS-White/**"]

[".config/awesome/vicious"]
  type = "archive"
  # renovate: currentValue=master
  url = "https://github.com/vicious-widgets/vicious/archive/4d3025400e565958aadb0738a1dba388fa543d44.zip"
  exact = true
  stripComponents = 1

[".config/awesome/bling"]
  type = "archive"
  # renovate: currentValue=master
  url = "https://github.com/BlingCorp/bling/archive/bcfb671248cf9ff636b7fd7d7120d8ed9deaa395.zip"
  exact = true
  stripComponents = 1

[".config/awesome/rubato"]
  type = "archive"
  # renovate: currentValue=main
  url = "https://github.com/andOrlando/rubato/archive/187d440f12f718f3ca78d8c234df7273bbc9e3f1.zip"
  exact = true
  stripComponents = 1
{{- end }}
