# [".config/nvim"]
#   type = "archive"
#   # renovate: currentValue=main
#   url = "https://github.com/kabinspace/AstroVim/archive/31cbff91fd5262c956e45b844a2f79b00c8be335.zip"
#   exact = false
#   stripComponents = 1

[".local/share/lunarvim/lvim"]
  type = "archive"
  # renovate: currentValue=rolling
  url = "https://github.com/LunarVim/LunarVim/archive/1ae89bee93a01f2c64884ae8bed3f28681c2abff.zip"
  exact = true
  stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}
