[".config/nvim"]
  type = "archive"
  # renovate: currentValue=main
  url = "https://github.com/kabinspace/AstroVim/archive/f683718f1293a7315971ebf9b4a02ba904a9ff37.zip"
  exact = false
  stripComponents = 1
  include = [
    "*/colors/**/*",
    "*/lua/**/*",
    "*/init.lua",
    "*/.luacheckrc",
    "*/.stylua.toml"
  ]
{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}
