[".config/nvim"]
  type = "archive"
  # renovate: currentValue=main
  url = "https://github.com/kabinspace/AstroVim/archive/ae8fe46d5854c2dc9ebb3192328aa6ea6a80e976.zip"
  exact = false
  stripComponents = 1
  # include = [
  #   "*/colors/**/*",
  #   "*/lua/**/*",
  #   "*/init.lua",
  #   "*/.luacheckrc",
  #   "*/.stylua.toml"
  # ]
[".local/share/lunarvim/lvim"]
  type = "archive"
  # renovate: currentValue=rolling
  url = "https://github.com/LunarVim/LunarVim/archive/10c7753d8e6f572974f9b9e0d0d8631cd13e60ea.zip"
  exact = true
  stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}

