# [".config/nvim"]
#   type = "archive"
#   # renovate: currentValue=main
#   url = "https://github.com/kabinspace/AstroVim/archive/f7d87bf55afaacc0a187b14da5b85d5da79d82be.zip"
#   exact = false
#   stripComponents = 1

[".local/share/lunarvim/lvim"]
  type = "archive"
  # renovate: currentValue=rolling
  url = "https://github.com/LunarVim/LunarVim/archive/84d91bd3be64db5b57744fe8e679da7e45e37055.zip"
  exact = true
  stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}
