# [".config/nvim"]
#   type = "archive"
#   # renovate: currentValue=main
#   url = "https://github.com/kabinspace/AstroVim/archive/859e215204f29af943a797a1ec768459ccaec6ba.zip"
#   exact = false
#   stripComponents = 1

[".local/share/lunarvim/lvim"]
  type = "archive"
  # renovate: currentValue=rolling
  url = "https://github.com/LunarVim/LunarVim/archive/0481ec8dddf4bd8ed81c10ae98807fec97f6f872.zip"
  exact = true
  stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}
