[".config/nvim"]
  type = "archive"
  # renovate: currentValue=main
  url = "https://github.com/kabinspace/AstroVim/archive/f1d960d7e33a5c1adf3eba0d9c4a3b25f6fdbc1a.zip"
  exact = false
  stripComponents = 1
  # include = [
  #   "*/colors/**/*",
  #   "*/lua/**/*",
  #   "*/init.lua",
  #   "*/.luacheckrc",
  #   "*/.stylua.toml"
  # ]
[".local/share/lunarvim/lvim"]
  type = "archive"
  # renovate: currentValue=rolling
  url = "https://github.com/LunarVim/LunarVim/archive/fcb16c0961cd2b6ca522a0b2088ad663fd605b85.zip"
  exact = true
  stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}

