# [".config/nvim"]
#   type = "archive"
#   url = "https://github.com/kabinspace/AstroVim/archive/1367d3bcff035c7f73bb849e7a55f3516e9cffa5.zip"
#   exact = false
#   stripComponents = 1

# [".local/share/lunarvim/lvim"]
#   type = "archive"
#   url = "https://github.com/LunarVim/LunarVim/archive/3de829e76ed3d90b25250b1ab76f6425146af9d2.zip"
#   exact = true
#   stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  # renovate: currentValue=master
  url = "https://github.com/vicious-widgets/vicious/archive/4d3025400e565958aadb0738a1dba388fa543d44.zip"
  exact = true
  stripComponents = 1
[".config/awesome/modules/bling"]
  type = "archive"
  # renovate: currentValue=master
  url = "https://github.com/BlingCorp/bling/archive/70c894e58bb88dea55e9799ad373fdaea309da9e.zip"
  exact = true
  stripComponents = 1
{{- end }}
