# [".config/nvim"]
#   type = "archive"
#   url = "https://github.com/kabinspace/AstroVim/archive/1367d3bcff035c7f73bb849e7a55f3516e9cffa5.zip"
#   exact = false
#   stripComponents = 1

# [".local/share/lunarvim/lvim"]
#   type = "archive"
#   url = "https://github.com/LunarVim/LunarVim/archive/3de829e76ed3d90b25250b1ab76f6425146af9d2.zip"
#   exact = true
#   stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".icons/macOS-Monterey"]
  type = "archive"
  url = "https://github.com/ful1e5/apple_cursor/releases/latest/download/macOS-Monterey.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"

[".icons/macOS-Monterey-White"]
  type = "archive"
  url = "https://github.com/ful1e5/apple_cursor/releases/latest/download/macOS-Monterey-White.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"

[".config/awesome/modules/vicious"]
  type = "archive"
  # renovate: currentValue=master
  url = "https://github.com/vicious-widgets/vicious/archive/4d3025400e565958aadb0738a1dba388fa543d44.zip"
  exact = true
  stripComponents = 1

[".config/awesome/modules/bling"]
  type = "archive"
  # renovate: currentValue=master
  url = "https://github.com/BlingCorp/bling/archive/5995a7f4b1850c66f9f7848c62c9e120b2079d87.zip"
  exact = true
  stripComponents = 1
{{- end }}
