[".config/nvim"]
  type = "archive"
  # renovate: currentValue=main
  url = "https://github.com/kabinspace/AstroVim/archive/186fd5c94b560b02a5528c0f50a6e4a0165a1592.zip"
  exact = false
  stripComponents = 1
  # include = [
  #   "*/colors/**/*",
  #   "*/lua/**/*",
  #   "*/init.lua",
  #   "*/.luacheckrc",
  #   "*/.stylua.toml"
  # ]
[".local/share/lunarvim/lvim"]
  type = "archive"
  # renovate: currentValue=rolling
  url = "https://github.com/LunarVim/LunarVim/archive/7807f147c192fdb6aec7659a3098b4bf31852fcd.zip"
  exact = true
  stripComponents = 1

{{- if eq .chezmoi.os "linux" }}
[".config/awesome/modules/vicious"]
  type = "archive"
  url = "https://github.com/vicious-widgets/vicious/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/awesome/modules/bling"]
  type = "archive"
  url = "https://github.com/BlingCorp/bling/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "72h"
{{- end }}

