shell = "bash -c '{}'"

# Xresources
[[items]]
file = "~/.Xresources"
template = "xresources"
subtemplate = "default-256"
start = "! Start flavours"
end = "! End flavours"

# Kitty
[[items]]
file = "~/.config/kitty/base16.conf"
template = "kitty"
subtemplate = "default-256"
rewrite = true

# Fish
[[items]]
file = "~/.config/fish/custom.d/colors.fish"
template = "fish"
rewrite = true

# Qtile
[[items]]
file = "~/.config/qtile/modules/vars.py"
template = "qtile"
start = "# Start flavours"
end = "# End flavours"

