# vim: ft=toml

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 30000

format = """
[ ](bold purple)\
$shell\
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$cmake\
$deno\
$golang\
$helm\
$lua\
$nodejs\
$python\
$terraform\
$vagrant\
$nix_shell\
$fill \
$memory_usage\
$sudo\
$cmd_duration\
$time\
$line_break\
$jobs\
$status\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 300

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 5
truncation_symbol = "…/"
read_only = " "
home_symbol = " "
truncate_to_repo = false

[fill]
symbol = "─"
style = "241"

[git_branch]
truncation_length = 30

[git_metrics]
disabled = false

[git_status]
# conflicted = ""
# up_to_date = ""
untracked = "?"
# stashed = ""
stashed = ""
modified = "!"
staged = "+"
# renamed = ""
deleted = "x"
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[kubernetes]
disabled = false
format = '[$symbol $context](bright-green) '
symbol = "\uf21a "
# [kubernetes.context_aliases]
# "default" = "homelab"

[time]
disabled = false

[shell]
disabled = false
